// Ray.so-inspired code block themes. Beyond colors, each theme also picks
// its own font, window chrome style, frame padding, border treatment, and
// optional background pattern — so themes feel genuinely different rather
// than just recolored.

export type CodeThemeFont = "geist-mono" | "jetbrains-mono" | "fira-code" | "ibm-plex-mono"
export type CodeThemeChrome = "dots" | "minimal" | "branded" | "none"
export type CodeThemePattern = "none" | "diagonal" | "grid" | "noise"
export type CodeThemeBorder = "none" | "subtle" | "strong" | "glow"
export type CodeThemeRadius = "sm" | "md" | "lg" | "xl"
export type CodeThemePadding = "sm" | "md" | "lg" | "xl"

export type CodeTheme = {
  id: string
  name: string
  frame: string
  pattern?: CodeThemePattern
  bg: string
  fg: string
  muted: string
  keyword: string
  string: string
  number: string
  comment: string
  function: string
  variable: string
  type: string
  punctuation: string
  font?: CodeThemeFont
  chrome?: CodeThemeChrome
  brandName?: string
  lineNumbers?: boolean
  framePadding?: CodeThemePadding
  windowRadius?: CodeThemeRadius
  windowBorder?: CodeThemeBorder
}

const g = (from: string, to: string) =>
  from === to ? from : `linear-gradient(135deg, ${from} 0%, ${to} 100%)`

export const CODE_THEMES: CodeTheme[] = [
  {
    id: "vercel",
    name: "Vercel",
    frame: g("#232323", "#1F1F1F"),
    bg: "#0a0a0a",
    fg: "hsla(0, 0%, 93%, 1)",
    muted: "hsla(0, 0%, 63%, 1)",
    keyword: "oklch(69.36% 0.2223 3.91)",
    string: "oklch(73.1% 0.2158 148.29)",
    number: "#ffffff",
    comment: "hsla(0, 0%, 63%, 1)",
    function: "oklch(69.87% 0.2037 309.51)",
    variable: "oklch(77.21% 0.1991 64.28)",
    type: "oklch(71.7% 0.1648 250.79360374054167)",
    punctuation: "hsla(0, 0%, 93%, 1)",
    font: "geist-mono",
    chrome: "minimal",
    framePadding: "md",
    windowRadius: "md",
    windowBorder: "subtle",
  },
  {
    id: "supabase",
    name: "Supabase",
    frame: g("#121212", "#121212"),
    bg: "#0b0b0b",
    fg: "#ffffff",
    muted: "#7e7e7e",
    keyword: "#bda4ff",
    string: "#ffcda1",
    number: "#ededed",
    comment: "#7e7e7e",
    function: "#3ecf8e",
    variable: "#ffffff",
    type: "#3ecf8e",
    punctuation: "#ffffff",
    font: "jetbrains-mono",
    chrome: "branded",
    brandName: "supabase",
    lineNumbers: true,
    framePadding: "md",
    windowRadius: "md",
    windowBorder: "subtle",
  },
  {
    id: "tailwind",
    name: "Tailwind",
    frame: g("#36B6F0", "#36B6F0"),
    pattern: "grid",
    bg: "#0b1220",
    fg: "#ffffff",
    muted: "#94a3b8",
    keyword: "#c4b5fd",
    string: "#fde68a",
    number: "#fbbf24",
    comment: "#64748b",
    function: "#60a5fa",
    variable: "#e2e8f0",
    type: "#5eead4",
    punctuation: "#cbd5e1",
    font: "fira-code",
    chrome: "minimal",
    lineNumbers: true,
    framePadding: "xl",
    windowRadius: "lg",
    windowBorder: "none",
  },
  {
    id: "openai",
    name: "OpenAI",
    frame: g("#000", "#000"),
    bg: "#0a0a0a",
    fg: "#ededed",
    muted: "#a0a0a0",
    keyword: "#2E95D3",
    string: "#DDBB88",
    number: "#ededed",
    comment: "#a0a0a0",
    function: "#00A67D",
    variable: "#ededed",
    type: "#2E95D3",
    punctuation: "#ededed",
    font: "ibm-plex-mono",
    chrome: "none",
    lineNumbers: true,
    framePadding: "xl",
    windowRadius: "sm",
    windowBorder: "subtle",
  },
  {
    id: "resend",
    name: "Resend",
    frame: g("#232323", "#000000"),
    bg: "#0a0a0a",
    fg: "#ffffff",
    muted: "#6b7280",
    keyword: "#a78bfa",
    string: "#86efac",
    number: "#ffffff",
    comment: "#6b7280",
    function: "#60a5fa",
    variable: "#f3f4f6",
    type: "#f59e0b",
    punctuation: "#d1d5db",
    font: "geist-mono",
    chrome: "minimal",
    framePadding: "md",
    windowRadius: "md",
    windowBorder: "strong",
  },
  {
    id: "noir",
    name: "Noir",
    frame: g("#2E2E2E", "#2E2E2E"),
    bg: "#111111",
    fg: "#ffffff",
    muted: "#7a7a7a",
    keyword: "#ADADAD",
    string: "#BFBFBF",
    number: "#FFFFFF",
    comment: "#5C5C5C",
    function: "#D1D1D1",
    variable: "#ADADAD",
    type: "#ADADAD",
    punctuation: "#D1D1D1",
    font: "ibm-plex-mono",
    chrome: "none",
    framePadding: "sm",
    windowRadius: "sm",
    windowBorder: "strong",
  },
  {
    id: "ice",
    name: "Ice",
    frame: g("#BFD4F1", "#345FBF"),
    bg: "#0f172a",
    fg: "#FFFFFF",
    muted: "#5C6A70",
    keyword: "#BFC4C9",
    string: "#92DEF6",
    number: "#00B0E9",
    comment: "#5C6A70",
    function: "#778CB6",
    variable: "#778CB6",
    type: "#00B0E9",
    punctuation: "#778CB6",
    font: "fira-code",
    chrome: "dots",
    framePadding: "lg",
    windowRadius: "xl",
    windowBorder: "none",
  },
  {
    id: "sand",
    name: "Sand",
    frame: g("#EED5B6", "#AF8856"),
    pattern: "noise",
    bg: "#1c1412",
    fg: "#FFFFFF",
    muted: "#837E77",
    keyword: "#D3B48C",
    string: "#C2B181",
    number: "#C2B181",
    comment: "#837E77",
    function: "#F4A361",
    variable: "#F4A361",
    type: "#C2B181",
    punctuation: "#F4A361",
    font: "ibm-plex-mono",
    chrome: "minimal",
    framePadding: "lg",
    windowRadius: "sm",
    windowBorder: "subtle",
  },
  {
    id: "forest",
    name: "Forest",
    frame: g("#506853", "#213223"),
    bg: "#0a1410",
    fg: "#FFFFFF",
    muted: "#555E56",
    keyword: "#AAB4A3",
    string: "#C9C8BC",
    number: "#AAB4A3",
    comment: "#555E56",
    function: "#87B882",
    variable: "#6B8F71",
    type: "#C9C7BC",
    punctuation: "#AAB4A3",
    font: "jetbrains-mono",
    chrome: "dots",
    framePadding: "lg",
    windowRadius: "lg",
    windowBorder: "none",
  },
  {
    id: "mono",
    name: "Mono",
    frame: g("#333", "#181818"),
    bg: "#0a0a0a",
    fg: "#ffffff",
    muted: "#666666",
    keyword: "#a7a7a7",
    string: "#a7a7a7",
    number: "#ffffff",
    comment: "#666666",
    function: "#ffffff",
    variable: "#a7a7a7",
    type: "#a7a7a7",
    punctuation: "#a7a7a7",
    font: "geist-mono",
    chrome: "none",
    framePadding: "sm",
    windowRadius: "sm",
    windowBorder: "none",
  },
  {
    id: "breeze",
    name: "Breeze",
    frame: g("#CF2F98", "#6A3DEC"),
    bg: "#1a0d1f",
    fg: "#FFFFFF",
    muted: "#8A757D",
    keyword: "#6599FF",
    string: "#E9AEFE",
    number: "#55E7B2",
    comment: "#8A757D",
    function: "#F8518D",
    variable: "#F8518D",
    type: "#49E8F2",
    punctuation: "#F8518D",
    font: "fira-code",
    chrome: "dots",
    framePadding: "md",
    windowRadius: "xl",
    windowBorder: "glow",
  },
  {
    id: "candy",
    name: "Candy",
    frame: g("#A58EFB", "#E9BFF8"),
    bg: "#1d1f21",
    fg: "#FFFFFF",
    muted: "#807796",
    keyword: "#FF659C",
    string: "#DFD473",
    number: "#7A7FFD",
    comment: "#807796",
    function: "#73DFA5",
    variable: "#1AC8FF",
    type: "#1AC8FF",
    punctuation: "#FF659C",
    font: "jetbrains-mono",
    chrome: "dots",
    framePadding: "md",
    windowRadius: "lg",
    windowBorder: "none",
  },
  {
    id: "crimson",
    name: "Crimson",
    frame: g("#FF6363", "#733434"),
    bg: "#1a0c0c",
    fg: "#FEFDFD",
    muted: "#895E60",
    keyword: "#EB6F6F",
    string: "#EBB99D",
    number: "#FDA97A",
    comment: "#895E60",
    function: "#C88E8E",
    variable: "#C88E8E",
    type: "#D15510",
    punctuation: "#EB6F6F",
    font: "ibm-plex-mono",
    chrome: "minimal",
    framePadding: "md",
    windowRadius: "md",
    windowBorder: "glow",
  },
  {
    id: "falcon",
    name: "Falcon",
    frame: g("#BDE3EC", "#363654"),
    pattern: "grid",
    bg: "#131325",
    fg: "#FFFFFF",
    muted: "#6D7E88",
    keyword: "#9AB6B2",
    string: "#6A8697",
    number: "#BD9C9C",
    comment: "#6D7E88",
    function: "#6D88BB",
    variable: "#6D88BB",
    type: "#799DB1",
    punctuation: "#9AB6B2",
    font: "jetbrains-mono",
    chrome: "dots",
    framePadding: "lg",
    windowRadius: "md",
    windowBorder: "subtle",
  },
  {
    id: "meadow",
    name: "Meadow",
    frame: g("#59D499", "#A0872D"),
    bg: "#0f1a10",
    fg: "#FFFFFF",
    muted: "#708B6C",
    keyword: "#6DD79F",
    string: "#E9EB9D",
    number: "#46B114",
    comment: "#708B6C",
    function: "#B3D767",
    variable: "#B3D767",
    type: "#E4B165",
    punctuation: "#6DD79F",
    font: "fira-code",
    chrome: "branded",
    brandName: "meadow.dev",
    lineNumbers: true,
    framePadding: "lg",
    windowRadius: "md",
    windowBorder: "none",
  },
  {
    id: "midnight",
    name: "Midnight",
    frame: g("#4CC8C8", "#202033"),
    pattern: "noise",
    bg: "#0c0c1a",
    fg: "#FFFFFF",
    muted: "#4A4C56",
    keyword: "#7DA9AB",
    string: "#6D86A4",
    number: "#75D2B1",
    comment: "#4A4C56",
    function: "#51D0F8",
    variable: "#51D0F8",
    type: "#9681C2",
    punctuation: "#7DA9AB",
    font: "jetbrains-mono",
    chrome: "dots",
    framePadding: "xl",
    windowRadius: "xl",
    windowBorder: "glow",
  },
  {
    id: "raindrop",
    name: "Raindrop",
    frame: g("#8EC7FB", "#1C55AA"),
    bg: "#0b1729",
    fg: "#E4F2FF",
    muted: "#6C808B",
    keyword: "#2ED9FF",
    string: "#9DD8EB",
    number: "#9984EE",
    comment: "#6C808B",
    function: "#1AD6B5",
    variable: "#1AD6B5",
    type: "#008BB7",
    punctuation: "#2ED9FF",
    font: "fira-code",
    chrome: "dots",
    lineNumbers: true,
    framePadding: "xl",
    windowRadius: "lg",
    windowBorder: "none",
  },
  {
    id: "sunset",
    name: "Sunset",
    frame: g("#FFCF73", "#FF7A2F"),
    pattern: "diagonal",
    bg: "#1a0f05",
    fg: "#FFFFFF",
    muted: "#878572",
    keyword: "#FFAF65",
    string: "#F9D38C",
    number: "#E7CF55",
    comment: "#878572",
    function: "#E2D66B",
    variable: "#E2D66B",
    type: "#E978A1",
    punctuation: "#FFAF65",
    font: "ibm-plex-mono",
    chrome: "minimal",
    framePadding: "xl",
    windowRadius: "md",
    windowBorder: "strong",
  },
]

export const DEFAULT_CODE_THEME_ID = "candy"

export function resolveCodeTheme(id: string | null | undefined): CodeTheme {
  const found = CODE_THEMES.find((t) => t.id === id)
  return found ?? CODE_THEMES.find((t) => t.id === DEFAULT_CODE_THEME_ID) ?? CODE_THEMES[0]
}

// CSS mappings used by the renderer
export const FONT_STACKS: Record<CodeThemeFont, string> = {
  "geist-mono": `"Geist Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, monospace`,
  "jetbrains-mono": `"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, monospace`,
  "fira-code": `"Fira Code", ui-monospace, SFMono-Regular, Menlo, Monaco, monospace`,
  "ibm-plex-mono": `"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, monospace`,
}

export const PADDING_CLASS: Record<CodeThemePadding, string> = {
  sm: "p-2",
  md: "p-3",
  lg: "p-5",
  xl: "p-7",
}

export const RADIUS_CLASS: Record<CodeThemeRadius, string> = {
  sm: "rounded-sm",
  md: "rounded-md",
  lg: "rounded-lg",
  xl: "rounded-2xl",
}
